_BASE_: base.yaml

OUTPUT_DIR: ./output/border_head_semantic_2601

DATASETS:
  TRAIN: ("manga_border_semantic_train",)
  TEST: ()

INPUT:
  DATASET_MAPPER_NAME: "mask_former_semantic"
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (1280,)
  MAX_SIZE_TRAIN: 2400
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1280
  MAX_SIZE_TEST: 2400
  SIZE_DIVISIBILITY: 32
  BORDER_SEMANTIC:
    BINARY_FROM_255: True
    THRESHOLD: 127
    UPSCALE_FACTOR: 1.5

MODEL:
  WEIGHTS: "output/251210_baseline/model_final.pth"
  META_ARCHITECTURE: "MaskDINO"
  SEM_SEG_HEAD:
    NAME: "MaskDINOHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 2
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    PIXEL_DECODER_NAME: "MaskDINOEncoder"
    DIM_FEEDFORWARD: 1024
    NUM_FEATURE_LEVELS: 3
    TOTAL_NUM_FEATURE_LEVELS: 3
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  BORDER_HEAD:
    ENABLED: True
    TRAIN_ONLY: True
    FREEZE_BASE: True
    HIDDEN_DIM: 128
    IMAGE_HIDDEN_DIM: 32
    LOSS_WEIGHT: 1.0
    BCE_WEIGHT: 1.0
    DICE_WEIGHT: 1.0
    POS_WEIGHT: 12.0
  MaskDINO:
    TRANSFORMER_DECODER_NAME: "MaskDINODecoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 4.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    BOX_WEIGHT: 5.0
    GIOU_WEIGHT: 2.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 300
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 9
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    INITIAL_PRED: True
    TWO_STAGE: True
    DN: "seg"
    DN_NUM: 100
    INITIALIZE_BOX_TYPE: "bitmask"
    TEST:
      SEMANTIC_ON: True
      INSTANCE_ON: False
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.25
      SEM_SEG_POSTPROCESSING_BEFORE_INFERENCE: True

SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 1.0e-04
  BASE_LR_END: 0.0
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  MAX_ITER: 3000
  CHECKPOINT_PERIOD: 250
  AMP:
    ENABLED: True

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 2

TEST:
  EVAL_PERIOD: 0
